name: Daily Python Script

on:
  schedule:
    - cron: '0 15 * * *' # 这会在每天的UTC时间的午夜执行

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10 # 或你想要使用的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果你有任何依赖，例如在requirements.txt中，你可以使用下面的命令进行安装
        pip install -r requests

    - name: Run script
      run: python checkin.py # 替换为你的脚本路径和名称
