name: Daily Python Script

on:
  watch:
    types: [started]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # 或你想要使用的Python版本

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: python checkin.py # 替换为你的脚本路径和名称

    - name: Send email
      run: |
        echo "Here is the content of the Python script's print statements:" > email_body.txt
        cat /home/runner/work/AutoStart/AutoStart/*.csv >> email_body.txt
        cat email_body.txt | mail -s "Python Script Output" ${{ secrets.GITHUB_EMAIL }}
